#!/bin/sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#       (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#           noncompliant, but you have some other compliant shell such as ksh or
#           bash, then to run this script, type that shell name before the whole
#           command line, like:
#
#               ksh Gradle
#
#           Busybox and similar reduced shells will NOT work, because this script
#           requires all of these POSIX shell features:
#             * functions;
#             * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#               «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#             * compound commands having a testable exit status, especially «case»;
#             * various built-in commands including «command», «set», and «ulimit».
#
#       (2) This script targets POSIX shells. Other shells may work, but are not
#           guaranteed to work. See also:
#           https://github.com/gradle/gradle/blob/HEAD/platforms/jvm/plugins-application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#
#           Important for Cygwin users:
#           - The script requires POSIX-compliant utilities like «grep», «sed», etc.
#           - On Windows, you must use Cygwin's own shell and utilities (like «find»)
#             rather than Windows versions.
#
#       (3) This script is generated from the Groovy template
#           https://github.com/gradle/gradle/blob/HEAD/platforms/jvm/plugins-application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#           within the Gradle project.
#
#           You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters here affects neither the number of
        # iterations, nor the values presented in `arg`.
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
fi


# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and optsEnvironmentVar are not
#     allowed to contain shell fragments or be folded.
#   * They are concatenated with space and the result is evaluated.
#   * The resulting string is passed to the java command.
#   * These are the parameters intended to be passed by this script.

# Collect command line arguments. Using quotes here is important to prevent
# word splitting and pathname expansion.
# For each argument, run through the following pipeline:
#   1. Grab argument (preserve whitespace)
#   2. Escape backslashes (for Windows paths)
#   3. Quote the argument (for command line safety)
eval set -- $(
    printf '%s\n' "$@" |
        awk '
        {
          gsub(/\\/, "\\\\")
          gsub(/\n/, "\\n")
          gsub(/\r/, "\\r")
          printf " \"%s\"", $0
        }
        END {
          print ""
        }
    '
)

APP_ARGS=$( printf '%s\n' "$@" | awk '
{
    gsub(/\\/, "\\\\")
    gsub(/\n/, "\\n")
    gsub(/\r/, "\\r")
    printf " \"%s\"", $0
}
END {
    print ""
}
'
)

# When using cygpath, we must quote the resulting value for the eval to work.
# But on other systems, we must not quote it.
quoted_app_args=
if "$cygwin" || "$msys" ; then
    # We must quote the result for eval.
    quoted_app_args=\"$APP_ARGS\"
fi

# Escape system property keys and values for java.
# This prevents issues when they contain special shell characters.
function escape_system_property() {
    printf '%s\n' "$1" | awk '
    {
        gsub(/\\/, "\\\\")
        gsub(/"/, "\\\"")
        printf "%s", $0
    }
'
}

function escape_system_property_value() {
    printf '%s\n' "$1" | awk '
    {
        gsub(/\\/, "\\\\")
        gsub(/"/, "\\\"")
        printf "%s", $0
    }
'
}

# Convert sysProps to escaped -Dkey=value arguments
# This will handle:
#   APP_HOME, gradleOpts, optsEnvironmentVar, -Dkey=value, etc.
collect_system_properties() {
    # The following are environment variables. They are never intended to be shell fragments.
    # shellcheck disable=SC2154
    for key in $APP_KEYS; do
        value=$(eval echo \"\$"$key"\")
        if [ -n "$value" ]; then
            printf '%s' "-D$(escape_system_property "$key")=$(escape_system_property_value "$value") "
        fi
    done
    # Collect additional -D options from command line (JAVA_OPTS, GRADLE_OPTS, etc.)
    # These need to be passed through as-is
    for arg do
        case $arg in
            -D*) printf '%s' "$arg " ;;
        esac
    done
}

# Append any remaining arguments from command line
# Append always because we are collecting properties for the exec JVM
APP_CMD_LINE_ARGS=$( collect_system_properties "$@" )
if [ -n "$APP_CMD_LINE_ARGS" ] ; then
    APP_CMD_LINE_ARGS=$( printf '%s\n' "$APP_CMD_LINE_ARGS" | awk '{print}' )
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters here affects neither the number of
        # iterations, nor the values presented in `arg`.
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
fi


# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and optsEnvironmentVar are not
#     allowed to contain shell fragments or be folded.
#   * They are concatenated with space and the result is evaluated.
#   * The resulting string is passed to the java command.
#   * These are the parameters intended to be passed by this script.

# Collect command line arguments. Using quotes here is important to prevent
# word splitting and pathname expansion.
# For each argument, run through the following pipeline:
#   1. Grab argument (preserve whitespace)
#   2. Escape backslashes (for Windows paths)
#   3. Quote the argument (for command line safety)
eval set -- $(
    printf '%s\n' "$@" |
        awk '
        {
          gsub(/\\/, "\\\\")
          gsub(/\n/, "\\n")
          gsub(/\r/, "\\r")
          printf " \"%s\"", $0
        }
        END {
          print ""
        }
    '
)

APP_ARGS=$( printf '%s\n' "$@" | awk '
{
    gsub(/\\/, "\\\\")
    gsub(/\n/, "\\n")
    gsub(/\r/, "\\r")
    printf " \"%s\"", $0
}
END {
    print ""
}
'
)

# When using cygpath, we must quote the resulting value for the eval to work.
# But on other systems, we must not quote it.
quoted_app_args=
if "$cygwin" || "$msys" ; then
    # We must quote the result for eval.
    quoted_app_args=\"$APP_ARGS\"
fi

# Escape system property keys and values for java.
# This prevents issues when they contain special shell characters.
function escape_system_property() {
    printf '%s\n' "$1" | awk '
    {
        gsub(/\\/, "\\\\")
        gsub(/"/, "\\\"")
        printf "%s", $0
    }
'
}

function escape_system_property_value() {
    printf '%s\n' "$1" | awk '
    {
        gsub(/\\/, "\\\\")
        gsub(/"/, "\\\"")
        printf "%s", $0
    }
'
}

# Convert sysProps to escaped -Dkey=value arguments
# This will handle:
#   APP_HOME, gradleOpts, optsEnvironmentVar, -Dkey=value, etc.
collect_system_properties() {
    # The following are environment variables. They are never intended to be shell fragments.
    # shellcheck disable=SC2154
    for key in $APP_KEYS; do
        value=$(eval echo \"\$"$key"\")
        if [ -n "$value" ]; then
            printf '%s' "-D$(escape_system_property "$key")=$(escape_system_property_value "$value") "
        fi
    done
    # Collect additional -D options from command line (JAVA_OPTS, GRADLE_OPTS, etc.)
    # These need to be passed through as-is
    for arg do
        case $arg in
            -D*) printf '%s' "$arg " ;;
        esac
    done
}

# Append any remaining arguments from command line
# Append always because we are collecting properties for the exec JVM
APP_CMD_LINE_ARGS=$( collect_system_properties "$@" )
if [ -n "$APP_CMD_LINE_ARGS" ] ; then
    APP_CMD_LINE_ARGS=$( printf '%s\n' "$APP_CMD_LINE_ARGS" | awk '{print}' )
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters here affects neither the number of
        # iterations, nor the values presented in `arg`.
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
fi


# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and optsEnvironmentVar are not
#     allowed to contain shell fragments or be folded.
#   * They are concatenated with space and the result is evaluated.
#   * The resulting string is passed to the java command.
#   * These are the parameters intended to be passed by this script.

# Collect command line arguments. Using quotes here is important to prevent
# word splitting and pathname expansion.
# For each argument, run through the following pipeline:
#   1. Grab argument (preserve whitespace)
#   2. Escape backslashes (for Windows paths)
#   3. Quote the argument (for command line safety)
eval set -- $(
    printf '%s\n' "$@" |
        awk '
        {
          gsub(/\\/, "\\\\")
          gsub(/\n/, "\\n")
          gsub(/\r/, "\\r")
          printf " \"%s\"", $0
        }
        END {
          print ""
        }
    '
)

APP_ARGS=$( printf '%s\n' "$@" | awk '
{
    gsub(/\\/, "\\\\")
    gsub(/\n/, "\\n")
    gsub(/\r/, "\\r")
    printf " \"%s\"", $0
}
END {
    print ""
}
'
)

# When using cygpath, we must quote the resulting value for the eval to work.
# But on other systems, we must not quote it.
quoted_app_args=
if "$cygwin" || "$msys" ; then
    # We must quote the result for eval.
    quoted_app_args=\"$APP_ARGS\"
fi

# Escape system property keys and values for java.
# This prevents issues when they contain special shell characters.
function escape_system_property() {
    printf '%s\n' "$1" | awk '
    {
        gsub(/\\/, "\\\\")
        gsub(/"/, "\\\"")
        printf "%s", $0
    }
'
}

function escape_system_property_value() {
    printf '%s\n' "$1" | awk '
    {
        gsub(/\\/, "\\\\")
        gsub(/"/, "\\\"")
        printf "%s", $0
    }
'
}

# Convert sysProps to escaped -Dkey=value arguments
# This will handle:
#   APP_HOME, gradleOpts, optsEnvironmentVar, -Dkey=value, etc.
collect_system_properties() {
    # The following are environment variables. They are never intended to be shell fragments.
    # shellcheck disable=SC2154
    for key in $APP_KEYS; do
        value=$(eval echo \"\$"$key"\")
        if [ -n "$value" ]; then
            printf '%s' "-D$(escape_system_property "$key")=$(escape_system_property_value "$value") "
        fi
    done
    # Collect additional -D options from command line (JAVA_OPTS, GRADLE_OPTS, etc.)
    # These need to be passed through as-is
    for arg do
        case $arg in
            -D*) printf '%s' "$arg " ;;
        esac
    done
}

# Append any remaining arguments from command line
# Append always because we are collecting properties for the exec JVM
APP_CMD_LINE_ARGS=$( collect_system_properties "$@" )
if [ -n "$APP_CMD_LINE_ARGS" ] ; then
    APP_CMD_LINE_ARGS=$( printf '%s\n' "$APP_CMD_LINE_ARGS" | awk '{print}' )
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters here affects neither the number of
        # iterations, nor the values presented in `arg`.
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
fi


# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and optsEnvironmentVar are not
#     allowed to contain shell fragments or be folded.
#   * They are concatenated with space and the result is evaluated.
#   * The resulting string is passed to the java command.
#   * These are the parameters intended to be passed by this script.

# Collect command line arguments. Using quotes here is important to prevent
# word splitting and pathname expansion.
# For each argument, run through the following pipeline:
#   1. Grab argument (preserve whitespace)
#   2. Escape backslashes (for Windows paths)
#   3. Quote the argument (for command line safety)
eval set -- $(
    printf '%s\n' "$@" |
        awk '
        {
          gsub(/\\/, "\\\\")
          gsub(/\n/, "\\n")
          gsub(/\r/, "\\r")
          printf " \"%s\"", $0
        }
        END {
          print ""
        }
    '
)

APP_ARGS=$( printf '%s\n' "$@" | awk '
{
    gsub(/\\/, "\\\\")
    gsub(/\n/, "\\n")
    gsub(/\r/, "\\r")
    printf " \"%s\"", $0
}
END {
    print ""
}
'
)

# When using cygpath, we must quote the resulting value for the eval to work.
# But on other systems, we must not quote it.
quoted_app_args=
if "$cygwin" || "$msys" ; then
    # We must quote the result for eval.
    quoted_app_args=\"$APP_ARGS\"
fi

# Escape system property keys and values for java.
# This prevents issues when they contain special shell characters.
function escape_system_property() {
    printf '%s\n' "$1" | awk '
    {
        gsub(/\\/, "\\\\")
        gsub(/"/, "\\\"")
        printf "%s", $0
    }
'
}

function escape_system_property_value() {
    printf '%s\n' "$1" | awk '
    {
        gsub(/\\/, "\\\\")
        gsub(/"/, "\\\"")
        printf "%s", $0
    }
'
}

# Convert sysProps to escaped -Dkey=value arguments
# This will handle:
#   APP_HOME, gradleOpts, optsEnvironmentVar, -Dkey=value, etc.
collect_system_properties() {
    # The following are environment variables. They are never intended to be shell fragments.
    # shellcheck disable=SC2154
    for key in $APP_KEYS; do
        value=$(eval echo \"\$"$key"\")
        if [ -n "$value" ]; then
            printf '%s' "-D$(escape_system_property "$key")=$(escape_system_property_value "$value") "
        fi
    done
    # Collect additional -D options from command line (JAVA_OPTS, GRADLE_OPTS, etc.)
    # These need to be passed through as-is
    for arg do
        case $arg in
            -D*) printf '%s' "$arg " ;;
        esac
    done
}

# Append any remaining arguments from command line
# Append always because we are collecting properties for the exec JVM
APP_CMD_LINE_ARGS=$( collect_system_properties "$@" )
if [ -n "$APP_CMD_LINE_ARGS" ] ; then
    APP_CMD_LINE_ARGS=$( printf '%s\n' "$APP_CMD_LINE_ARGS" | awk '{print}' )
fi

# Execute Gradle
"$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$@"
